name: Publish Docker image
on: [push]
jobs:
  check-types-and-eslint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: |
          npm install

      - name: Check types (server)
        run: npm run typesonce

      - name: Check types (client)
        run: cd client && npm run typesonce

      - name: Run tests
        run: cd client && npm test
